name: 524_project_env
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - ipykernel
  - matplotlib=3.8.0
  - pandas=2.1.1
  - scikit-learn=1.3.1
  - altair=5.1.2
  - pip=23.3.1
  - python=3.12.0
  - vl-convert-python  
  - vegafusion  
  - vegafusion-python-embed  
  - vegafusion-jupyter  
  - click=8.1.7
  - jupyter-book=0.15.1
  - importlib-metadata=4.13.0
  - pip:
    - pytest==7.4.4

